const app=document.getElementById('app'),restoreInput=document.getElementById('restoreInput');
const S={user:sessionStorage.getItem('te_user'),companyId:sessionStorage.getItem('te_company'),screen:'gateway',stack:[],focusKey:null};
const DB={companies:()=>JSON.parse(localStorage.getItem('te_companies')||'[]'),saveCompanies:x=>localStorage.setItem('te_companies',JSON.stringify(x)),data:id=>JSON.parse(localStorage.getItem('te_data_'+id)||'null'),save:(id,x)=>localStorage.setItem('te_data_'+id,JSON.stringify(x))};
const uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const defaultGroups=()=>['Capital Account','Bank Accounts','Bank OD A/c','Cash-in-Hand','Current Assets','Current Liabilities','Deposits (Asset)','Direct Expenses','Direct Incomes','Duties & Taxes','Expenses (Direct)','Expenses (Indirect)','Fixed Assets','Income (Direct)','Income (Indirect)','Investments','Loans & Advances (Asset)','Loans (Liability)','Provisions','Purchase Accounts','Reserves & Surplus','Retained Earnings','Sales Accounts','Secured Loans','Stock-in-Hand','Sundry Creditors','Sundry Debtors','Suspense A/c','Unsecured Loans'].map((name,i)=>({id:'g'+i,name,parent:'Primary',nature:groupNature(name),system:true}));
function groupNature(n){if(/Capital|Liabil|Creditor|Loan|Provision|Reserve|OD/.test(n))return'Liability';if(/Sales|Income/.test(n))return'Income';if(/Purchase|Expense|Duties/.test(n))return'Expense';return'Asset'}
function seed(){return{groups:defaultGroups(),ledgers:[],vouchers:[],lastEntry:null}}
function company(){return DB.companies().find(x=>x.id===S.companyId)}
function data(){let d=DB.data(S.companyId);if(!d){d=seed();DB.save(S.companyId,d)}if(!d.vouchers)d.vouchers=[];return d}
function saveData(d){DB.save(S.companyId,d)}
function hk(label,key){const i=label.toLowerCase().indexOf(key.toLowerCase());if(i<0)return esc(label);return esc(label.slice(0,i))+`<u class="hotkey">${esc(label[i])}</u>`+esc(label.slice(i+1))}
function shell(title,body){return `<div class="top"><div class="brand">Tabaja ERP <small>V2.2</small></div><div class="topnav"><button>K: Company</button><button>Y: Data</button><button>Z: Exchange</button><button id="gotoTop">G: Go To</button><button>O: Import</button><button>E: Export</button></div></div><div class="strip">${esc(title)}</div>${body}<div class="status"><span>Q: Quit</span><span>A: Accept</span><span>Esc: Back</span><span>Enter: Select</span></div>`}
function render(){if(!S.user)return login();if(!S.companyId||!company())return hub();gateway()}
function login(){S.screen='login';app.innerHTML=`<div class="login"><form class="loginbox" id="f"><h1>Tabaja ERP</h1><p>Personal Accounting System</p><div class="field"><label>User Name</label><input name="u" value="admin"></div><div class="field"><label>Password</label><input name="p" type="password" value="1234"></div><button class="btn primary" style="width:100%">Sign In</button><div class="note">First login: admin / 1234</div></form></div>`;f.onsubmit=e=>{e.preventDefault();let x=new FormData(f);if(x.get('u')==='admin'&&x.get('p')==='1234'){S.user='admin';sessionStorage.setItem('te_user','admin');hub()}else alert('Incorrect login')}}
function hub(){S.screen='hub';S.stack=[];let cs=DB.companies();app.innerHTML=shell('Company Selection',`<main class="hub"><div class="toolbar hub-tools"><button class="btn primary" id="newC">${hk('Create Company','C')}</button><button class="btn" id="backup">${hk('Backup Data','B')}</button><button class="btn" id="restore">${hk('Restore Data','R')}</button><button class="btn" id="logout">${hk('Logout','L')}</button></div><div class="cards">${cs.length?cs.map((c,i)=>`<div class="card company-card"><h3>${esc(c.name)}</h3><p>${esc(c.country||'Sierra Leone')}</p><p>Financial year: ${esc(c.fy)}</p><button class="btn primary open-company" data-open="${c.id}">${hk('Open Company','O')}</button></div>`).join(''):'<div class="card"><h3>No company created</h3><p>Create your first company.</p></div>'}</div></main>`);newC.onclick=companyForm;logout.onclick=()=>{sessionStorage.clear();S.user=null;login()};backup.onclick=backupAll;restore.onclick=()=>restoreInput.click();document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openCompany(b.dataset.open));setTimeout(()=>document.querySelector('.open-company')?.focus(),0)}
function openCompany(id){S.companyId=id;sessionStorage.setItem('te_company',id);gateway()}
function companyForm(){S.screen='companyForm';app.innerHTML=shell('Company Creation',`<main class="hub"><form class="card" id="cf"><div class="form-grid"><div class="field"><label>Company Name *</label><input name="name" required></div><div class="field"><label>Mailing Name</label><input name="mailing"></div><div class="field full"><label>Address</label><textarea name="address"></textarea></div><div class="field"><label>Country</label><input name="country" value="Sierra Leone"></div><div class="field"><label>Financial year beginning</label><input type="date" name="fy" value="2026-04-01"></div><div class="field"><label>Books beginning</label><input type="date" name="books" value="2026-04-01"></div><div class="field"><label>Base Currency</label><input name="currency" value="NLe"></div></div><div class="actions"><button type="button" class="btn" id="cancel">Cancel</button><button class="btn primary">Create Company</button></div></form></main>`);cancel.onclick=hub;cf.onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(cf));let c={id:uid('c'),...o};let cs=DB.companies();cs.push(c);DB.saveCompanies(cs);DB.save(c.id,seed());openCompany(c.id)};setupFormKeyboard(cf,hub)}
function gateway(){S.screen='gateway';let c=company(),d=data();app.innerHTML=shell(c.name,`<main class="screen"><div class="gateway"><section class="company-info"><div class="meta"><div><small>CURRENT PERIOD</small><b>${esc(c.fy)} onward</b></div><div><small>CURRENT DATE</small><b>${new Date().toLocaleDateString('en-GB')}</b></div><div><small>NAME OF COMPANY</small><h2>${esc(c.name)}</h2></div><div><small>DATE OF LAST ENTRY</small><b>${d.lastEntry||'No entries yet'}</b></div></div></section><aside class="panel"><div class="panel-title">Gateway of Tabaja ERP</div><div class="section-title">MASTERS</div><button class="menu-btn" data-key="c" id="create">${hk('Create','C')}</button><button class="menu-btn" data-key="a" id="alter">${hk('Alter','A')}</button><button class="menu-btn" data-key="h" id="coa">C${hk('hart of Accounts','H')}</button><div class="section-title">TRANSACTIONS</div><button class="menu-btn" data-key="v" id="vouchers">${hk('Vouchers','V')}</button><button class="menu-btn" data-key="y" id="daybook">Da${hk('y Book','Y')}</button><div class="section-title">REPORTS</div><button class="menu-btn" data-key="b" id="bs">${hk('Balance Sheet','B')}</button><button class="menu-btn" data-key="p" id="pl">${hk('Profit & Loss A/c','P')}</button><button class="menu-btn" data-key="s" id="stock">${hk('Stock Summary','S')}</button><button class="menu-btn" data-key="d" id="display">${hk('Display More Reports','D')}</button><button class="menu-btn" data-key="o" id="dashboard">Dashb${hk('oard','O')}</button><div class="section-title"></div><button class="menu-btn" data-key="q" id="close">${hk('Quit','Q')}</button></aside></div></main>`);bindMenu('.panel .menu-btn');create.onclick=createMenu;alter.onclick=alterMenu;coa.onclick=chart;display.onclick=displayMenu;close.onclick=()=>quitPopup('Close company?',()=>{S.companyId=null;sessionStorage.removeItem('te_company');hub()});['vouchers','daybook','bs','pl','stock','dashboard'].forEach(id=>document.getElementById(id).onclick=()=>toast('This module is prepared for the next build.'));gotoTop.onclick=goToPopup}
function overlay(title,inner,wide=false){let x=document.createElement('div');x.id='ov';x.className='modal-backdrop';x.innerHTML=`<div class="modal ${wide?'wide':''}"><div class="modal-title">${title}</div><div class="modal-body">${inner}</div></div>`;document.body.appendChild(x);return x}
function createMenu(){S.screen='createMenu';let o=overlay('Master Creation',`<div class="master-list"><h4>Accounting Masters</h4><button data-key="g" id="cg">${hk('Group','G')}</button><button data-key="l" id="cl">${hk('Ledger','L')}</button><button data-key="c" id="cc">${hk('Cost Centre','C')}</button><button data-key="u" id="cur">C${hk('urrency','U')}</button><button data-key="v" id="vt">${hk('Voucher Type','V')}</button><h4>Inventory Masters</h4><button data-key="s" id="sg">${hk('Stock Group','S')}</button><button data-key="a" id="sc">Stock C${hk('ategory','A')}</button><button data-key="i" id="si">Stock ${hk('Item','I')}</button><button data-key="n" id="unit">U${hk('nit','N')}</button><button data-key="o" id="loc">L${hk('ocation','O')}</button></div>`);bindMenu('.master-list > button');cg.onclick=createGroup;cl.onclick=createLedger;['cc','cur','vt','sg','sc','si','unit','loc'].forEach(id=>document.getElementById(id).onclick=()=>toast('Coming in the next build.'))}
function alterMenu(){S.screen='alterMenu';let o=overlay('Master Alteration',`<div class="master-list"><h4>Accounting Masters</h4><button data-key="g" id="ag">${hk('Group','G')}</button><button data-key="l" id="al">${hk('Ledger','L')}</button></div>`);bindMenu('.master-list > button');ag.onclick=()=>toast('Group alteration coming next.');al.onclick=()=>ledgerList('alter')}
function displayMenu(){S.screen='displayMenu';let o=overlay('Display More Reports',`<div class="master-list"><h4>ACCOUNTING</h4><button data-key="t" id="dt">${hk('Trial Balance','T')}</button><button data-key="d" id="dd">${hk('Day Book','D')}</button><button data-key="c" id="dc">${hk('Cash Flow','C')}</button><button data-key="f" id="df">${hk('Funds Flow','F')}</button><h4><button class="inline-head" data-key="a" id="ab">${hk('Account Books','A')}</button></h4><button data-key="s" id="sa">${hk('Statements of Accounts','S')}</button><h4>INVENTORY</h4><button data-key="i" id="ib">${hk('Inventory Books','I')}</button><button data-key="e" id="si">Stat${hk('ements of Inventory','E')}</button></div>`);bindMenu('.master-list button');dd.onclick=()=>toast('Day Book will show vouchers after voucher entry is added.');ab.onclick=accountBooks;['dt','dc','df','sa','ib','si'].forEach(id=>document.getElementById(id).onclick=()=>toast('This report is prepared for a later build.'))}
function accountBooks(){document.getElementById('ov')?.remove();S.screen='accountBooks';let o=overlay('Account Books',`<div class="master-list"><button data-key="l" id="abl">${hk('Ledger','L')}</button><button data-key="c" id="cashbook">${hk('Cash/Bank Book(s)','C')}</button><button data-key="g" id="groupsum">${hk('Group Summary','G')}</button><button data-key="s" id="salesreg">${hk('Sales Register','S')}</button><button data-key="p" id="purreg">${hk('Purchase Register','P')}</button></div>`);bindMenu('.master-list button');abl.onclick=()=>ledgerList('display');['cashbook','groupsum','salesreg','purreg'].forEach(id=>document.getElementById(id).onclick=()=>toast('Coming after voucher entry.'))}
function createGroup(){document.getElementById('ov')?.remove();S.screen='groupForm';let d=data();let o=overlay('Group Creation',`<form id="gf"><div class="form-grid"><div class="field full"><label>Name *</label><input name="name" required autofocus></div><div class="field"><label>Under</label><select name="parent"><option>Primary</option>${d.groups.map(g=>`<option>${esc(g.name)}</option>`).join('')}</select></div><div class="field"><label>Nature</label><select name="nature"><option>Asset</option><option>Liability</option><option>Income</option><option>Expense</option></select></div></div><div class="actions"><button type="button" class="btn" id="cancelG">Cancel</button><button class="btn primary">Accept</button></div></form>`);cancelG.onclick=()=>{o.remove();createMenu()};gf.onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(gf));d.groups.push({id:uid('g'),...v,system:false});saveData(d);toast('Group created successfully');gf.reset();gf.elements.name.focus()};setupFormKeyboard(gf,()=>{o.remove();createMenu()})}
function createLedger(editId=null){document.getElementById('ov')?.remove();S.screen='ledgerForm';let d=data(),old=editId?d.ledgers.find(x=>x.id===editId):null;let o=overlay(old?'Ledger Alteration':'Ledger Creation',`<form id="lf"><div class="form-grid"><div class="field"><label>Name *</label><input name="name" required autofocus value="${esc(old?.name||'')}"></div><div class="field"><label>Alias</label><input name="alias" value="${esc(old?.alias||'')}"></div><div class="field"><label>Under *</label><select name="groupId" required>${d.groups.map(g=>`<option value="${g.id}" ${old?.groupId===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select></div><div class="field"><label>Opening Balance</label><input name="opening" type="number" step="0.01" value="${old?.opening??0}"></div><div class="field"><label>Balance Type</label><select name="balanceType"><option ${old?.balanceType==='Dr'?'selected':''}>Dr</option><option ${old?.balanceType==='Cr'?'selected':''}>Cr</option></select></div><div class="field"><label>Provide bank details</label><select name="bank"><option ${old?.bank!=='Yes'?'selected':''}>No</option><option ${old?.bank==='Yes'?'selected':''}>Yes</option></select></div><div class="field full"><label>Mailing Address</label><textarea name="address">${esc(old?.address||'')}</textarea></div></div><div class="actions"><button type="button" class="btn" id="cancelL">Cancel</button><button class="btn primary">Accept</button></div></form>`);cancelL.onclick=()=>{o.remove();editId?ledgerList('alter'):createMenu()};lf.onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(lf));v.opening=Number(v.opening||0);if(old)Object.assign(old,v);else d.ledgers.push({id:uid('l'),...v});saveData(d);toast(old?'Ledger altered successfully':'Ledger created successfully');if(old){o.remove();ledgerList('alter')}else{lf.reset();lf.elements.opening.value=0;lf.elements.name.focus()}};setupFormKeyboard(lf,()=>{o.remove();editId?ledgerList('alter'):createMenu()})}
function ledgerList(mode='display'){document.getElementById('ov')?.remove();S.screen='ledgerList';let d=data();let o=overlay(mode==='alter'?'Select Ledger to Alter':'Select Ledger',`<div class="list-search"><label>Name of Ledger</label><input id="ledgerSearch" autocomplete="off"></div><div class="scroll-list" id="ledgerRows"></div>`);const draw=()=>{let q=ledgerSearch.value.toLowerCase();let rows=d.ledgers.filter(l=>l.name.toLowerCase().includes(q)||String(l.alias||'').toLowerCase().includes(q));ledgerRows.innerHTML=rows.length?rows.map(l=>`<button class="list-row" data-id="${l.id}">${esc(l.name)}</button>`).join(''):'<div class="empty-row">No ledgers found</div>';bindMenu('#ledgerRows .list-row');document.querySelectorAll('#ledgerRows .list-row').forEach(b=>b.onclick=()=>mode==='alter'?createLedger(b.dataset.id):ledgerDisplay(b.dataset.id))};ledgerSearch.oninput=draw;draw();setTimeout(()=>ledgerSearch.focus(),0)}
function ledgerDisplay(id){document.getElementById('ov')?.remove();S.screen='ledgerDisplay';let d=data(),l=d.ledgers.find(x=>x.id===id),g=d.groups.find(x=>x.id===l.groupId),vs=d.vouchers.filter(v=>v.lines?.some(x=>x.ledgerId===id));let signed=(l.balanceType==='Cr'?-1:1)*Number(l.opening||0);let current=vs.reduce((sum,v)=>sum+v.lines.filter(x=>x.ledgerId===id).reduce((a,x)=>a+Number(x.debit||0)-Number(x.credit||0),0),0);let closing=signed+current;app.innerHTML=shell(company().name,`<main class="hub ledger-page"><div class="report-head"><h2>Ledger Vouchers</h2><div><b>Ledger: ${esc(l.name)}</b><br><small>Under: ${esc(g?.name||'')}</small></div></div><table class="table"><thead><tr><th>Date</th><th>Particulars</th><th>Vch Type</th><th>Vch No.</th><th>Debit</th><th>Credit</th></tr></thead><tbody>${vs.length?vs.map(v=>`<tr><td>${esc(v.date)}</td><td>${esc(v.particulars||'')}</td><td>${esc(v.type||'')}</td><td>${esc(v.number||'')}</td><td class="right">${Number(v.debit||0).toFixed(2)}</td><td class="right">${Number(v.credit||0).toFixed(2)}</td></tr>`).join(''):`<tr><td colspan="6" class="empty-row">No voucher entries yet</td></tr>`}</tbody></table><div class="balances"><div>Opening Balance: <b>${Math.abs(signed).toFixed(2)} ${signed<0?'Cr':'Dr'}</b></div><div>Current Total: <b>${Math.abs(current).toFixed(2)} ${current<0?'Cr':'Dr'}</b></div><div>Closing Balance: <b>${Math.abs(closing).toFixed(2)} ${closing<0?'Cr':'Dr'}</b></div></div></main>`)}
function chart(){S.screen='chart';let d=data();let rows=d.groups.map(g=>{let ls=d.ledgers.filter(l=>l.groupId===g.id);return `<tr><td><b>${esc(g.name)}</b>${g.system?' <span class="badge">System</span>':''}</td><td>${esc(g.parent)}</td><td>${esc(g.nature)}</td><td>${ls.length}</td></tr>${ls.map(l=>`<tr><td style="padding-left:35px">↳ ${esc(l.name)}</td><td>${esc(g.name)}</td><td>Ledger</td><td class="right">${l.opening.toFixed(2)} ${esc(l.balanceType)}</td></tr>`).join('')}`}).join('');app.innerHTML=shell(company().name,`<main class="hub"><h2>Chart of Accounts</h2><table class="table"><thead><tr><th>Name</th><th>Under</th><th>Type / Nature</th><th>Count / Opening</th></tr></thead><tbody>${rows}</tbody></table></main>`)}
function goToPopup(){if(document.getElementById('ov'))return;let o=overlay('Go To',`<div class="list-search"><input id="gotoInput" placeholder="Type DAL, CAL, AAL, DD, TB..."></div><div class="goto-help">DAL = Display Account Books Ledger<br>CAL = Create Ledger<br>AAL = Alter Ledger<br>DD = Day Book<br>TB = Trial Balance<br>CHA = Chart of Accounts</div>`);setTimeout(()=>gotoInput.focus(),0);gotoInput.onkeydown=e=>{if(e.key==='Enter'){let code=gotoInput.value.trim().toUpperCase();o.remove();if(code==='DAL')ledgerList('display');else if(code==='CAL')createLedger();else if(code==='AAL')ledgerList('alter');else if(code==='DD')toast('Day Book will show vouchers after voucher entry is added.');else if(code==='TB')toast('Trial Balance is prepared for a later build.');else if(code==='CHA')chart();else toast('Shortcut not found')}}}
function quitPopup(text,onYes){if(document.getElementById('quitOv'))return;let q=document.createElement('div');q.id='quitOv';q.className='modal-backdrop quit-backdrop';q.innerHTML=`<div class="quit-box"><div>${esc(text)}</div><div class="quit-actions"><button data-choice="yes">Yes</button><button class="active" data-choice="no">No</button></div></div>`;document.body.appendChild(q);let buttons=[...q.querySelectorAll('button')],i=1;const set=n=>{i=(n+2)%2;buttons.forEach((b,j)=>b.classList.toggle('active',j===i));buttons[i].focus()};buttons.forEach((b,j)=>b.onclick=()=>{if(j===0){q.remove();onYes()}else q.remove()});q.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'||e.key==='Tab'){e.preventDefault();set(i===0?1:0)}else if(e.key==='Enter'){e.preventDefault();buttons[i].click()}else if(e.key==='Escape'||e.key.toLowerCase()==='n'){e.preventDefault();q.remove()}else if(e.key.toLowerCase()==='y'){e.preventDefault();buttons[0].click()}};set(1)}
function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function backupAll(){let out={version:'2.2',companies:DB.companies(),data:{}};out.companies.forEach(c=>out.data[c.id]=DB.data(c.id));let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download='tabaja-erp-v2-2-backup.json';a.click()}
restoreInput.onchange=async e=>{try{let o=JSON.parse(await e.target.files[0].text());DB.saveCompanies(o.companies||[]);Object.entries(o.data||{}).forEach(([id,v])=>DB.save(id,v));hub()}catch{alert('Invalid backup file')}};
function focusables(root=document){return [...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null)}
function bindMenu(selector){const items=[...document.querySelectorAll(selector)];if(!items.length)return;let i=0;const set=n=>{i=(n+items.length)%items.length;items.forEach((x,j)=>{x.classList.toggle('active',j===i);x.tabIndex=j===i?0:-1});items[i].focus({preventScroll:true})};items.forEach((x,j)=>x.addEventListener('focus',()=>{i=j;items.forEach((a,k)=>a.classList.toggle('active',k===i))}));set(0)}
function setupFormKeyboard(form,onCancel){form.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();onCancel();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();form.requestSubmit();return}if(e.key==='Enter'&&e.target.tagName!=='TEXTAREA'){e.preventDefault();const list=focusables(form);let i=list.indexOf(e.target),next=list[i+1];if(!next||e.target.type==='submit')form.requestSubmit();else next.focus()}});setTimeout(()=>focusables(form)[0]?.focus(),0)}
function handleMenuKeys(e,root=document){const items=[...root.querySelectorAll('.menu-btn,.master-list button,.list-row')].filter(x=>x.offsetParent!==null);if(!items.length)return false;let i=items.indexOf(document.activeElement);if(i<0)i=items.findIndex(x=>x.classList.contains('active'));if(e.key==='ArrowDown'){e.preventDefault();items[(i+1+items.length)%items.length].focus();return true}if(e.key==='ArrowUp'){e.preventDefault();items[(i-1+items.length)%items.length].focus();return true}if(e.key==='Enter'&&items.includes(document.activeElement)){e.preventDefault();document.activeElement.click();return true}if(!e.ctrlKey&&!e.altKey&&!e.metaKey&&e.key.length===1){let k=e.key.toLowerCase(),match=items.find(x=>x.dataset.key===k);if(match){e.preventDefault();match.click();return true}}return false}
document.addEventListener('keydown',e=>{
 if(document.getElementById('quitOv'))return;
 const ov=document.getElementById('ov');
 if(e.key==='Escape'){
   e.preventDefault();
   if(ov){ov.remove();if(S.screen==='ledgerList' || S.screen==='accountBooks')displayMenu();else if(S.screen==='displayMenu'||S.screen==='createMenu'||S.screen==='alterMenu')gateway();return}
   if(S.screen==='ledgerDisplay'){ledgerList('display');return}
   if(S.screen==='chart'){gateway();return}
   if(S.screen==='gateway'){S.companyId=null;sessionStorage.removeItem('te_company');hub();return}
   if(S.screen==='hub'){quitPopup('Quit?',()=>{sessionStorage.clear();S.user=null;login()});return}
   if(S.screen==='companyForm'){hub();return}
 }
 if(e.key==='F4'){e.preventDefault();goToPopup();return}
 if(ov){if(handleMenuKeys(e,ov))return}
 else if(handleMenuKeys(e,document))return;
 if(!ov&&S.screen==='gateway'&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&e.key.length===1){let map={c:createMenu,a:alterMenu,h:chart,d:displayMenu,g:goToPopup,q:()=>quitPopup('Close company?',()=>{S.companyId=null;sessionStorage.removeItem('te_company');hub()})};let fn=map[e.key.toLowerCase()];if(fn){e.preventDefault();fn()}}
 if(!ov&&S.screen==='hub'&&e.key==='Enter'&&document.activeElement?.classList.contains('open-company')){e.preventDefault();document.activeElement.click()}
});
render();
