const S={screen:'login',stack:[],menuIndex:0,listIndex:0,goto:false,gotoIndex:0,gotoQuery:'',currentLedger:null,returnFocus:null};
const app=document.querySelector('#app'),overlay=document.querySelector('#overlay-root');
const defaults=[
 {name:'Cash',group:'Cash-in-Hand',opening:0},{name:'Bank Account',group:'Bank Accounts',opening:0},
 {name:'Capital Account',group:'Capital Account',opening:0},{name:'Sales Account',group:'Sales Accounts',opening:0},
 {name:'Purchase Account',group:'Purchase Accounts',opening:0},{name:'Office Expenses',group:'Indirect Expenses',opening:0}
];
function db(){return JSON.parse(localStorage.getItem('tabajaERP23')||'null')||{company:{name:'Tabaja Demo Company',currency:'NLe',fy:'01-01-2026'},ledgers:defaults,vouchers:[]}}
function save(d){localStorage.setItem('tabajaERP23',JSON.stringify(d))}
function push(screen,extra={}){S.stack.push({screen:S.screen,menuIndex:S.menuIndex,listIndex:S.listIndex,currentLedger:S.currentLedger});S.screen=screen;Object.assign(S,extra);render()}
function back(){if(S.goto){closeGoto();return}if(S.stack.length){const p=S.stack.pop();Object.assign(S,p);render();return}if(S.screen!=='gateway'){S.screen='gateway';render();return}quitDialog()}
function shell(content,side=''){const d=db();return `<div class="app"><div class="topbar"><div class="brand">TABAJA <span>ERP</span> <small>V2.3</small></div><div class="company-tag">${d.company.name}</div></div><div class="workspace"><main class="main">${content}</main><aside class="side"><h3>Keyboard Panel</h3>${side||defaultSide()}</aside></div><div class="footer"><span><b>G</b>: Go To</span><span><b>Esc</b>: Back</span><span><b>Enter</b>: Select</span><span><b>↑ ↓</b>: Navigate</span></div></div>`}
function defaultSide(){return `<div class="hint"><b>F2</b> Period</div><div class="hint"><b>F3</b> Company</div><div class="hint"><b>C</b> Create</div><div class="hint"><b>D</b> Display</div><div class="hint"><b>DAL</b> Ledger</div><div class="hint"><b>DD</b> Day Book</div><div class="hint"><b>TB</b> Trial Balance</div>`}
const gatewayItems=[
 {label:'<span class="hot">C</span>reate',action:()=>push('createMenu')},
 {label:'<span class="hot">A</span>lter',action:()=>push('alterMenu')},
 {label:'<span class="hot">D</span>isplay More Reports',action:()=>push('displayMenu')},
 {label:'Chart of Accounts',action:()=>push('chart')},
 {label:'Backup / Restore',action:()=>push('backup')},
 {label:'<span class="hot">Q</span>uit',action:quitDialog}
];
function render(){overlay.innerHTML='';if(S.screen==='login')return renderLogin();if(S.screen==='companySelect')return renderCompanySelect();if(S.screen==='gateway')return renderGateway();if(S.screen==='createMenu')return renderSimpleMenu('Create',['Ledger','Group'],[()=>push('ledgerForm'),()=>toast('Group creation comes in next build')]);if(S.screen==='alterMenu')return renderLedgerList('Alter Ledger',true);if(S.screen==='displayMenu')return renderSimpleMenu('Display More Reports',['Account Books','Day Book','Trial Balance','Chart of Accounts'],[()=>push('accountBooks'),()=>push('daybook'),()=>push('trial'),()=>push('chart')]);if(S.screen==='accountBooks')return renderSimpleMenu('Account Books',['Ledger'],[()=>push('ledgerList')]);if(S.screen==='ledgerList')return renderLedgerList('Select Ledger',false);if(S.screen==='ledgerForm')return renderLedgerForm();if(S.screen==='ledgerView')return renderLedgerView();if(S.screen==='chart')return renderChart();if(S.screen==='daybook')return renderDaybook();if(S.screen==='trial')return renderTrial();if(S.screen==='backup')return renderBackup();}
function renderLogin(){app.innerHTML=`<div class="login"><div class="login-left"><h1>Tabaja <span>ERP</span></h1><p>Manage. Control. Grow.</p><p class="small">Keyboard-first accounting prototype</p></div><div class="login-right"><div class="login-card"><h2>Welcome Back</h2><label>User Name</label><input id="user" value="admin"><label>Password</label><input id="pass" type="password" value="1234"><button class="btn primary" id="loginBtn">Sign In</button><p class="small">Demo login: admin / 1234</p></div></div></div>`;setTimeout(()=>user.focus());loginBtn.onclick=()=>{if(user.value==='admin'&&pass.value==='1234'){S.screen='companySelect';render()}else toast('Incorrect login')};}
function renderCompanySelect(){const d=db();app.innerHTML=`<div class="login-right" style="height:100vh"><div class="login-card"><h2>Select Company</h2><div class="menu-item active" id="companyRow">${d.company.name}</div><button class="btn primary" id="openCompany" style="margin-top:14px">Open Company</button><button class="btn" id="newCompany" style="margin-top:8px">Create New Company</button><p class="small">Press Enter to open.</p></div></div>`;setTimeout(()=>openCompany.focus());openCompany.onclick=()=>{S.screen='gateway';S.stack=[];render()};newCompany.onclick=()=>{const name=prompt('Company name');if(name){d.company.name=name;save(d);render()}}}
function renderGateway(){app.innerHTML=shell(`<div class="gateway"><div class="gateway-box"><div class="gateway-head">Gateway of Tabaja ERP</div><div class="menu"><div class="section-label">Masters & Reports</div>${gatewayItems.map((x,i)=>`<div class="menu-item ${i===S.menuIndex?'active':''}" data-i="${i}">${x.label}</div>`).join('')}</div></div></div>`);document.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>{S.menuIndex=+el.dataset.i;gatewayItems[S.menuIndex].action()})}
function renderSimpleMenu(title,items,actions){app.innerHTML=shell(`<div class="screen"><div class="title">${title}</div><div class="panel"><div class="menu">${items.map((x,i)=>`<div class="menu-item ${i===S.menuIndex?'active':''}" data-i="${i}">${x}</div>`).join('')}</div></div></div>`);document.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>{S.menuIndex=+el.dataset.i;actions[S.menuIndex]()});S._actions=actions;S._items=items}
function renderLedgerList(title,alter){const d=db(),items=d.ledgers;S.listIndex=Math.min(S.listIndex,Math.max(0,items.length-1));app.innerHTML=shell(`<div class="screen"><div class="title">${title}</div><div class="panel"><div class="search-line"><input id="ledgerSearch" placeholder="Type to search ledgers"></div><div id="ledgerRows">${ledgerRows(items)}</div></div></div>`);function ledgerRows(list){return `<div class="list-row header"><div>Ledger Name</div><div>Group</div></div>`+list.map((x,i)=>`<div class="list-row ${i===S.listIndex?'active':''}" data-i="${i}"><div>${x.name}</div><div>${x.group}</div></div>`).join('')}
 ledgerSearch.oninput=()=>{const q=ledgerSearch.value.toLowerCase();const f=items.filter(x=>x.name.toLowerCase().includes(q));S._filtered=f;S.listIndex=0;ledgerRowsEl().innerHTML=ledgerRows(f);bindRows()};function ledgerRowsEl(){return document.querySelector('#ledgerRows')}function bindRows(){document.querySelectorAll('[data-i]').forEach(el=>el.onclick=()=>openLedger((S._filtered||items)[+el.dataset.i]))}function openLedger(l){S.currentLedger=l.name;push(alter?'ledgerForm':'ledgerView',{editLedger:alter?l.name:null})}bindRows();setTimeout(()=>ledgerSearch.focus());S._list=items;S._alter=alter}
function renderLedgerForm(){const d=db();const existing=S.editLedger?d.ledgers.find(x=>x.name===S.editLedger):null;app.innerHTML=shell(`<div class="screen"><div class="title">${existing?'Alter':'Create'} Ledger</div><div class="form"><div class="form-grid"><label>Ledger Name</label><input id="lname" value="${existing?.name||''}"><label>Under Group</label><select id="lgroup">${['Capital Account','Current Assets','Current Liabilities','Cash-in-Hand','Bank Accounts','Sales Accounts','Purchase Accounts','Direct Expenses','Indirect Expenses','Sundry Debtors','Sundry Creditors'].map(g=>`<option ${existing?.group===g?'selected':''}>${g}</option>`).join('')}</select><label>Opening Balance</label><input id="lopen" type="number" value="${existing?.opening||0}"></div><div class="actions"><button class="btn" id="cancel">Cancel</button><button class="btn primary" id="saveLedger">Accept (Ctrl+A)</button></div></div></div>`);setTimeout(()=>lname.focus());cancel.onclick=back;saveLedger.onclick=submitLedger;S._submit=submitLedger;function submitLedger(){const name=lname.value.trim();if(!name)return toast('Enter ledger name');if(existing){existing.name=name;existing.group=lgroup.value;existing.opening=+lopen.value||0}else{d.ledgers.push({name,group:lgroup.value,opening:+lopen.value||0})}save(d);S.editLedger=null;toast('Ledger saved');back()}}
function renderLedgerView(){const d=db(),l=d.ledgers.find(x=>x.name===S.currentLedger)||d.ledgers[0];const rows=d.vouchers.filter(v=>v.ledger===l.name);const debit=rows.reduce((s,v)=>s+(v.debit||0),0),credit=rows.reduce((s,v)=>s+(v.credit||0),0),close=(l.opening||0)+debit-credit;app.innerHTML=shell(`<div class="screen"><div class="title">Ledger Vouchers — ${l.name}</div><div class="panel"><div class="ledger-summary"><div class="metric">Opening Balance<b>${fmt(l.opening)}</b></div><div class="metric">Current Total<b>${fmt(debit-credit)}</b></div><div class="metric">Closing Balance<b>${fmt(close)}</b></div></div><div class="voucher-table"><div class="voucher-row header"><div>Date</div><div>Particulars</div><div>Debit</div><div>Credit</div></div>${rows.length?rows.map(v=>`<div class="voucher-row"><div>${v.date}</div><div>${v.particulars}</div><div>${fmt(v.debit)}</div><div>${fmt(v.credit)}</div></div>`).join(''):`<div class="empty">No vouchers recorded yet.</div>`}</div></div></div>`,`<div class="hint"><b>F2</b> Period</div><div class="hint"><b>F3</b> Company</div><div class="hint"><b>F4</b> Ledger</div><div class="hint"><b>Enter</b> Drill Down</div><div class="hint"><b>G</b> Go To</div>`)}
function renderChart(){const d=db();app.innerHTML=shell(`<div class="screen"><div class="title">Chart of Accounts</div><div class="panel"><div class="list-row header"><div>Ledger Name</div><div>Group</div></div>${d.ledgers.map((x,i)=>`<div class="list-row"><div>${x.name}</div><div>${x.group}</div></div>`).join('')}</div></div>`)}
function renderDaybook(){app.innerHTML=shell(`<div class="screen"><div class="title">Day Book</div><div class="panel"><div class="empty">No vouchers recorded yet. Voucher Entry begins in V2.4.</div></div></div>`)}
function renderTrial(){const d=db();app.innerHTML=shell(`<div class="screen"><div class="title">Trial Balance</div><div class="panel"><div class="list-row header"><div>Particulars</div><div>Closing Balance</div></div>${d.ledgers.map(x=>`<div class="list-row"><div>${x.name}</div><div>${fmt(x.opening)}</div></div>`).join('')}</div></div>`)}
function renderBackup(){app.innerHTML=shell(`<div class="screen"><div class="title">Backup / Restore</div><div class="form"><p>Download a JSON backup or restore it later.</p><div class="actions"><button class="btn" id="restoreBtn">Restore</button><button class="btn primary" id="backupBtn">Download Backup</button></div><input type="file" id="restoreFile" accept="application/json" hidden></div></div>`);backupBtn.onclick=()=>{const blob=new Blob([JSON.stringify(db(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Tabaja-ERP-Backup.json';a.click()};restoreBtn.onclick=()=>restoreFile.click();restoreFile.onchange=async()=>{try{save(JSON.parse(await restoreFile.files[0].text()));toast('Backup restored');render()}catch{toast('Invalid backup file')}}}
const gotoItems=[
 {code:'DAL',name:'Ledger Vouchers',go:()=>push('ledgerList')},{code:'DD',name:'Day Book',go:()=>push('daybook')},{code:'TB',name:'Trial Balance',go:()=>push('trial')},{code:'COA',name:'Chart of Accounts',go:()=>push('chart')},{code:'CAL',name:'Create Ledger',go:()=>push('ledgerForm')},{code:'AAL',name:'Alter Ledger',go:()=>push('alterMenu')},{code:'BS',name:'Balance Sheet (Coming Soon)',go:()=>toast('Balance Sheet is planned')},{code:'PL',name:'Profit & Loss (Coming Soon)',go:()=>toast('Profit & Loss is planned')}
];
function openGoto(){if(S.screen==='login'||S.screen==='companySelect')return;S.goto=true;S.gotoIndex=0;S.gotoQuery='';renderGoto()}
function renderGoto(){const filtered=gotoItems.filter(x=>(x.code+' '+x.name).toLowerCase().includes(S.gotoQuery.toLowerCase()));S._gotoFiltered=filtered;overlay.innerHTML=`<div class="overlay"><div class="goto"><div class="goto-head">Go To</div><div class="goto-search"><input id="gotoSearch" value="${S.gotoQuery}" placeholder="Search reports or type DAL, DD, TB..."></div><div class="goto-list">${filtered.map((x,i)=>`<div class="goto-item ${i===S.gotoIndex?'active':''}"><b>${x.code}</b><span>${x.name}</span></div>`).join('')}</div></div></div>`;setTimeout(()=>{gotoSearch.focus();gotoSearch.setSelectionRange(gotoSearch.value.length,gotoSearch.value.length)});gotoSearch.oninput=()=>{S.gotoQuery=gotoSearch.value;S.gotoIndex=0;renderGoto()}}
function closeGoto(){S.goto=false;S.gotoQuery='';overlay.innerHTML=''}
function activateGoto(){const x=(S._gotoFiltered||gotoItems)[S.gotoIndex];if(x){closeGoto();x.go()}}
function quitDialog(){overlay.innerHTML=`<div class="dialog-wrap"><div class="dialog"><h3>Quit</h3><p>Do you want to close the company?</p><div class="actions"><button class="btn" id="noQuit">No</button><button class="btn primary" id="yesQuit">Yes</button></div></div></div>`;setTimeout(()=>noQuit.focus());noQuit.onclick=()=>overlay.innerHTML='';yesQuit.onclick=()=>{overlay.innerHTML='';S.screen='companySelect';S.stack=[];render()}}
function fmt(n){return `${db().company.currency} ${(Number(n)||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.append(e);setTimeout(()=>e.remove(),1800)}
let seq='';let seqTimer;
window.addEventListener('keydown',e=>{
 if(e.ctrlKey&&e.key.toLowerCase()==='a'&&S._submit){e.preventDefault();S._submit();return}
 if(document.querySelector('.dialog-wrap')){if(e.key==='Escape'){overlay.innerHTML=''}return}
 if(S.goto){if(e.key==='Escape'){e.preventDefault();closeGoto();return}if(e.key==='ArrowDown'){e.preventDefault();S.gotoIndex=Math.min(S.gotoIndex+1,(S._gotoFiltered||gotoItems).length-1);renderGoto();return}if(e.key==='ArrowUp'){e.preventDefault();S.gotoIndex=Math.max(0,S.gotoIndex-1);renderGoto();return}if(e.key==='Enter'){e.preventDefault();activateGoto();return}return}
 if(e.key==='Escape'){e.preventDefault();back();return}
 if(e.key.toLowerCase()==='g'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();openGoto();return}
 if(S.screen==='gateway'){
  if(e.key==='ArrowDown'){e.preventDefault();S.menuIndex=(S.menuIndex+1)%gatewayItems.length;render();return}
  if(e.key==='ArrowUp'){e.preventDefault();S.menuIndex=(S.menuIndex-1+gatewayItems.length)%gatewayItems.length;render();return}
  if(e.key==='Enter'){e.preventDefault();gatewayItems[S.menuIndex].action();return}
  const k=e.key.toLowerCase();if(k==='c')return gatewayItems[0].action();if(k==='a')return gatewayItems[1].action();if(k==='d')return gatewayItems[2].action();if(k==='q')return quitDialog();
 }
 if(S._actions&&['createMenu','displayMenu','accountBooks'].includes(S.screen)){
  if(e.key==='ArrowDown'){e.preventDefault();S.menuIndex=(S.menuIndex+1)%S._items.length;render();return}
  if(e.key==='ArrowUp'){e.preventDefault();S.menuIndex=(S.menuIndex-1+S._items.length)%S._items.length;render();return}
  if(e.key==='Enter'){e.preventDefault();S._actions[S.menuIndex]();return}
 }
 if(['ledgerList','alterMenu'].includes(S.screen)&&!['INPUT'].includes(document.activeElement.tagName)){
  const list=S._filtered||S._list||[];if(e.key==='ArrowDown'){e.preventDefault();S.listIndex=Math.min(S.listIndex+1,list.length-1);render();return}if(e.key==='ArrowUp'){e.preventDefault();S.listIndex=Math.max(0,S.listIndex-1);render();return}if(e.key==='Enter'&&list[S.listIndex]){e.preventDefault();S.currentLedger=list[S.listIndex].name;push(S._alter?'ledgerForm':'ledgerView',{editLedger:S._alter?list[S.listIndex].name:null});return}
 }
 if(!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&/^[a-z]$/i.test(e.key)){
  seq+=(e.key.toUpperCase());clearTimeout(seqTimer);seqTimer=setTimeout(()=>seq='',650);const exact=gotoItems.find(x=>x.code===seq);if(exact){seq='';exact.go()}
 }
});
render();
