const app=document.getElementById('app'),restoreInput=document.getElementById('restoreInput');
const S={user:sessionStorage.getItem('te_user'),companyId:sessionStorage.getItem('te_company'),view:'gateway',screen:'gateway'};
const DB={companies:()=>JSON.parse(localStorage.getItem('te_companies')||'[]'),saveCompanies:x=>localStorage.setItem('te_companies',JSON.stringify(x)),data:id=>JSON.parse(localStorage.getItem('te_data_'+id)||'null'),save:(id,x)=>localStorage.setItem('te_data_'+id,JSON.stringify(x))};
const uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const defaultGroups=()=>['Capital Account','Bank Accounts','Bank OD A/c','Cash-in-Hand','Current Assets','Current Liabilities','Deposits (Asset)','Direct Expenses','Direct Incomes','Duties & Taxes','Expenses (Direct)','Expenses (Indirect)','Fixed Assets','Income (Direct)','Income (Indirect)','Investments','Loans & Advances (Asset)','Loans (Liability)','Provisions','Purchase Accounts','Reserves & Surplus','Retained Earnings','Sales Accounts','Secured Loans','Stock-in-Hand','Sundry Creditors','Sundry Debtors','Suspense A/c','Unsecured Loans'].map((name,i)=>({id:'g'+i,name,parent:'Primary',nature:groupNature(name),system:true}));
function groupNature(n){if(/Capital|Liabil|Creditor|Loan|Provision|Reserve|OD/.test(n))return'Liability';if(/Sales|Income/.test(n))return'Income';if(/Purchase|Expense|Duties/.test(n))return'Expense';return'Asset'}
function seed(){return{groups:defaultGroups(),ledgers:[],vouchers:[],lastEntry:null}}
function company(){return DB.companies().find(x=>x.id===S.companyId)}function data(){let d=DB.data(S.companyId);if(!d){d=seed();DB.save(S.companyId,d)}return d}function saveData(d){DB.save(S.companyId,d)}
function shell(title,body){return `<div class="top"><div class="brand">Tabaja ERP <small>V2.1</small></div><div class="topnav"><button>K: Company</button><button>Y: Data</button><button>Z: Exchange</button><button>G: Go To</button><button>O: Import</button><button>E: Export</button></div></div><div class="strip">${esc(title)}</div>${body}<div class="status"><span>Q: Quit</span><span>A: Accept</span><span>Esc: Back</span><span>Enter: Select</span></div>`}
function render(){if(!S.user)return login();if(!S.companyId||!company())return hub();gateway()}
function login(){app.innerHTML=`<div class="login"><form class="loginbox" id="f"><h1>Tabaja ERP</h1><p>Personal Accounting System</p><div class="field"><label>User Name</label><input name="u" value="admin"></div><div class="field"><label>Password</label><input name="p" type="password" value="1234"></div><button class="btn primary" style="width:100%">Sign In</button><div class="note">First login: admin / 1234</div></form></div>`;f.onsubmit=e=>{e.preventDefault();let x=new FormData(f);if(x.get('u')==='admin'&&x.get('p')==='1234'){S.user='admin';sessionStorage.setItem('te_user','admin');render()}else alert('Incorrect login')}}
function hub(){let cs=DB.companies();app.innerHTML=shell('Company Selection',`<main class="hub"><div class="toolbar"><button class="btn primary" id="newC">Create Company</button><button class="btn" id="backup">Backup Data</button><button class="btn" id="restore">Restore Data</button><button class="btn" id="logout">Logout</button></div><div class="cards">${cs.length?cs.map(c=>`<div class="card"><h3>${esc(c.name)}</h3><p>${esc(c.country||'Sierra Leone')}</p><p>Financial year: ${esc(c.fy)}</p><button class="btn primary" data-open="${c.id}">Open Company</button></div>`).join(''):'<div class="card"><h3>No company created</h3><p>Create your first company.</p></div>'}</div></main>`);newC.onclick=companyForm;logout.onclick=()=>{sessionStorage.clear();S.user=null;render()};backup.onclick=backupAll;restore.onclick=()=>restoreInput.click();document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{S.companyId=b.dataset.open;sessionStorage.setItem('te_company',S.companyId);render()})}
function companyForm(){app.innerHTML=shell('Company Creation',`<main class="hub"><form class="card" id="cf"><div class="form-grid"><div class="field"><label>Company Name *</label><input name="name" required></div><div class="field"><label>Mailing Name</label><input name="mailing"></div><div class="field full"><label>Address</label><textarea name="address"></textarea></div><div class="field"><label>Country</label><input name="country" value="Sierra Leone"></div><div class="field"><label>Financial year beginning</label><input type="date" name="fy" value="2026-04-01"></div><div class="field"><label>Books beginning</label><input type="date" name="books" value="2026-04-01"></div><div class="field"><label>Base Currency</label><input name="currency" value="NLe"></div></div><div class="actions"><button type="button" class="btn" id="cancel">Cancel</button><button class="btn primary">Create Company</button></div></form></main>`);cancel.onclick=hub;cf.onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(cf));let c={id:uid('c'),...o};let cs=DB.companies();cs.push(c);DB.saveCompanies(cs);DB.save(c.id,seed());S.companyId=c.id;sessionStorage.setItem('te_company',c.id);render()}}
function gateway(){S.screen='gateway';let c=company(),d=data();app.innerHTML=shell(c.name,`<main class="screen"><div class="gateway"><section class="company-info"><div class="meta"><div><small>CURRENT PERIOD</small><b>${esc(c.fy)} onward</b></div><div><small>CURRENT DATE</small><b>${new Date().toLocaleDateString('en-GB')}</b></div><div><small>NAME OF COMPANY</small><h2>${esc(c.name)}</h2></div><div><small>DATE OF LAST ENTRY</small><b>${d.lastEntry||'No entries yet'}</b></div></div></section><aside class="panel"><div class="panel-title">Gateway of Tabaja ERP</div><div class="section-title">MASTERS</div><button class="menu-btn" id="create">Create</button><button class="menu-btn" id="coa">Chart of Accounts</button><div class="section-title">TRANSACTIONS</div><button class="menu-btn" id="vouchers">Vouchers</button><button class="menu-btn" id="daybook">Day Book</button><div class="section-title">REPORTS</div><button class="menu-btn" id="trial">Trial Balance</button><button class="menu-btn" id="pl">Profit & Loss A/c</button><button class="menu-btn" id="bs">Balance Sheet</button><button class="menu-btn" id="stock">Stock Summary</button><div class="section-title"></div><button class="menu-btn" id="close">Close Company</button></aside></div></main>`);activateKeyboardMenu('.panel .menu-btn');create.onclick=createMenu;coa.onclick=chart;close.onclick=()=>{S.companyId=null;sessionStorage.removeItem('te_company');hub()};['vouchers','daybook','trial','pl','bs','stock'].forEach(id=>document.getElementById(id).onclick=()=>toast('This module is prepared for the next build.'))}
function overlay(title,inner,wide=false){let x=document.createElement('div');x.id='ov';x.className='modal-backdrop';x.innerHTML=`<div class="modal ${wide?'wide':''}"><div class="modal-title">${title}</div><div class="modal-body">${inner}</div></div>`;document.body.appendChild(x);return x}
function createMenu(){let o=overlay('Master Creation',`<div class="master-list"><h4>Accounting Masters</h4><button id="cg">Group</button><button id="cl">Ledger</button><button id="cc">Cost Centre</button><button id="cur">Currency</button><button id="vt">Voucher Type</button><h4>Inventory Masters</h4><button id="sg">Stock Group</button><button id="sc">Stock Category</button><button id="si">Stock Item</button><button id="unit">Unit</button><button id="loc">Location</button><div class="actions"><button class="btn" id="x">Close</button></div></div>`);activateKeyboardMenu('.master-list > button:not(.btn)');x.onclick=()=>o.remove();cg.onclick=createGroup;cl.onclick=createLedger;['cc','cur','vt','sg','sc','si','unit','loc'].forEach(id=>document.getElementById(id).onclick=()=>toast('Coming in the next build.'))}
function createGroup(){document.getElementById('ov')?.remove();let d=data();let o=overlay('Group Creation',`<form id="gf"><div class="form-grid"><div class="field full"><label>Name *</label><input name="name" required autofocus></div><div class="field"><label>Under</label><select name="parent"><option>Primary</option>${d.groups.map(g=>`<option>${esc(g.name)}</option>`).join('')}</select></div><div class="field"><label>Nature</label><select name="nature"><option>Asset</option><option>Liability</option><option>Income</option><option>Expense</option></select></div></div><div class="actions"><button type="button" class="btn" id="cancelG">Cancel</button><button class="btn primary">Accept</button></div></form>`);cancelG.onclick=()=>o.remove();gf.onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(gf));d.groups.push({id:uid('g'),...v,system:false});saveData(d);o.remove();toast('Group created successfully')}}
function createLedger(){document.getElementById('ov')?.remove();let d=data();let o=overlay('Ledger Creation',`<form id="lf"><div class="form-grid"><div class="field"><label>Name *</label><input name="name" required autofocus></div><div class="field"><label>Alias</label><input name="alias"></div><div class="field"><label>Under *</label><select name="groupId" required>${d.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select></div><div class="field"><label>Opening Balance</label><input name="opening" type="number" step="0.01" value="0"></div><div class="field"><label>Balance Type</label><select name="balanceType"><option>Dr</option><option>Cr</option></select></div><div class="field"><label>Provide bank details</label><select name="bank"><option>No</option><option>Yes</option></select></div><div class="field full"><label>Mailing Address</label><textarea name="address"></textarea></div></div><div class="actions"><button type="button" class="btn" id="cancelL">Cancel</button><button class="btn primary">Accept</button></div></form>`);cancelL.onclick=()=>o.remove();lf.onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(lf));d.ledgers.push({id:uid('l'),...v,opening:Number(v.opening||0)});saveData(d);o.remove();toast('Ledger created successfully')}}
function chart(){S.screen='chart';let d=data();let rows=d.groups.map(g=>{let ls=d.ledgers.filter(l=>l.groupId===g.id);return `<tr><td><b>${esc(g.name)}</b>${g.system?' <span class="badge">System</span>':''}</td><td>${esc(g.parent)}</td><td>${esc(g.nature)}</td><td>${ls.length}</td></tr>${ls.map(l=>`<tr><td style="padding-left:35px">↳ ${esc(l.name)}</td><td>${esc(g.name)}</td><td>Ledger</td><td class="right">${l.opening.toFixed(2)} ${esc(l.balanceType)}</td></tr>`).join('')}`}).join('');app.innerHTML=shell(company().name,`<main class="hub"><div class="toolbar"><button class="btn" id="back">Back</button><button class="btn primary" id="newG">Create Group</button><button class="btn primary" id="newL">Create Ledger</button></div><h2>Chart of Accounts</h2><table class="table"><thead><tr><th>Name</th><th>Under</th><th>Type / Nature</th><th>Count / Opening</th></tr></thead><tbody>${rows}</tbody></table></main>`);back.onclick=gateway;newG.onclick=createGroup;newL.onclick=createLedger}
function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function backupAll(){let out={version:'2.0',companies:DB.companies(),data:{}};out.companies.forEach(c=>out.data[c.id]=DB.data(c.id));let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download='tabaja-erp-v2-backup.json';a.click()}
restoreInput.onchange=async e=>{try{let o=JSON.parse(await e.target.files[0].text());DB.saveCompanies(o.companies||[]);Object.entries(o.data||{}).forEach(([id,v])=>DB.save(id,v));hub()}catch{alert('Invalid backup file')}};
function focusables(root=document){return [...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null)}
function activateKeyboardMenu(selector){
 const items=[...document.querySelectorAll(selector)]; if(!items.length)return;
 let i=0; const set=n=>{i=(n+items.length)%items.length;items.forEach((x,j)=>x.classList.toggle('active',j===i));items[i].focus({preventScroll:true})};
 items.forEach((x,j)=>{x.tabIndex=j===0?0:-1;x.addEventListener('focus',()=>set(j));}); set(0);
}
function setupFormKeyboard(form,onCancel){
 const els=focusables(form).filter(x=>x.type!=='button' || x.type==='submit');
 form.addEventListener('keydown',e=>{
   if(e.key==='Escape'){e.preventDefault();onCancel();return}
   if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();form.requestSubmit();return}
   if(e.key==='Enter' && e.target.tagName!=='TEXTAREA'){
     e.preventDefault();const list=focusables(form);let i=list.indexOf(e.target);let next=list[i+1];
     if(!next || e.target.type==='submit') form.requestSubmit(); else next.focus();
   }
 });
 setTimeout(()=>focusables(form)[0]?.focus(),0)
}
const oldCompanyForm=companyForm; companyForm=function(){oldCompanyForm();setupFormKeyboard(document.getElementById('cf'),hub)};
const oldCreateGroup=createGroup; createGroup=function(){oldCreateGroup();setupFormKeyboard(document.getElementById('gf'),()=>{document.getElementById('ov')?.remove();createMenu()})};
const oldCreateLedger=createLedger; createLedger=function(){oldCreateLedger();setupFormKeyboard(document.getElementById('lf'),()=>{document.getElementById('ov')?.remove();createMenu()})};
document.addEventListener('keydown',e=>{
 const ov=document.getElementById('ov');
 if(e.key==='Escape'){
   e.preventDefault();
   if(ov){ov.remove();return}
   if(S.screen==='chart'){gateway();return}
   if(S.companyId){S.companyId=null;sessionStorage.removeItem('te_company');hub();return}
 }
 if(!ov && S.screen==='gateway'){
   const items=[...document.querySelectorAll('.panel .menu-btn')];let i=items.findIndex(x=>x.classList.contains('active'));
   if(e.key==='ArrowDown'){e.preventDefault();i=(i+1+items.length)%items.length;items[i].focus();}
   if(e.key==='ArrowUp'){e.preventDefault();i=(i-1+items.length)%items.length;items[i].focus();}
   if(e.key==='Enter'&&document.activeElement?.classList.contains('menu-btn')){e.preventDefault();document.activeElement.click()}
 }
 if(ov){
   const items=[...ov.querySelectorAll('.master-list > button:not(.btn)')];let i=items.findIndex(x=>x.classList.contains('active'));
   if(items.length&&e.key==='ArrowDown'){e.preventDefault();i=(i+1+items.length)%items.length;items[i].focus()}
   if(items.length&&e.key==='ArrowUp'){e.preventDefault();i=(i-1+items.length)%items.length;items[i].focus()}
   if(items.length&&e.key==='Enter'&&document.activeElement?.closest('.master-list')){e.preventDefault();document.activeElement.click()}
 }
});render();
